### ISSUE TITLE
macOS 13.6 无法运行 mlx

### ISSUE THREAD

**Issue by greenhand0403** [linyiLYi/bilibot#5]
首先我是先从10.16系统下安装Anaconda开始，直到看到报错信息说mlx需要macOS 13.5+以上版本，于是更新系统到13.6
之前遇到的问题1，无法安装mlx
执行
`conda install -c conda-forge mlx`
解决
```
Channels:
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/bilibot

  added / updated specs:
    - mlx


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libblas-3.9.0              |22_osx64_openblas          14 KB  conda-forge
    libcxx-17.0.6              |       h88467a6_0         1.2 MB  conda-forge
    libgfortran-5.0.0          |13_2_0_h97931a8_3         108 KB  conda-forge
    libgfortran5-13.2.0        |       h2873a65_3         1.5 MB  conda-forge
    liblapack-3.9.0            |22_osx64_openblas          14 KB  conda-forge
    libopenblas-0.3.27         |openmp_hfef2a42_0         5.8 MB  conda-forge
    llvm-openmp-18.1.5         |       h39e0ece_0         293 KB  conda-forge
    mlx-0.7.0                  |  py310heb360e1_0         2.5 MB  conda-forge
    openssl-3.3.0              |       hd75f5a5_0         2.4 MB  conda-forge
    python_abi-3.10            |          2_cp310           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        13.8 MB

The following NEW packages will be INSTALLED:

  libblas            conda-forge/osx-64::libblas-3.9.0-22_osx64_openblas 
  libcxx             conda-forge/osx-64::libcxx-17.0.6-h88467a6_0 
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-13_2_0_h97931a8_3 
  libgfortran5       conda-forge/osx-64::libgfortran5-13.2.0-h2873a65_3 
  liblapack          conda-forge/osx-64::liblapack-3.9.0-22_osx64_openblas 
  libopenblas        conda-forge/osx-64::libopenblas-0.3.27-openmp_hfef2a42_0 
  llvm-openmp        conda-forge/osx-64::llvm-openmp-18.1.5-h39e0ece_0 
  mlx                conda-forge/osx-64::mlx-0.7.0-py310heb360e1_0 
  python_abi         conda-forge/osx-64::python_abi-3.10-2_cp310 

The following packages will be UPDATED:

  openssl              pkgs/main::openssl-3.0.13-hca72f7f_1 --> conda-forge::openssl-3.3.0-hd75f5a5_0 


Proceed ([y]/n)? y


Downloading and Extracting Packages:
                                                                                
Preparing transaction: done                                                     
Verifying transaction: done                                                     
Executing transaction: done
```
现在遇到的问题2，不知从何下手（已尝试①卸载Anaconda，重新走一遍流程问题仍然存在）
执行
`python -m mlx_lm.lora --model models/Qwen1.5-32B-Chat --data data/ --train --iters 1000 --batch-size 16 --lora-layers 12`
报错
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx/_os_warning.py", line 7, in <module>
    raise ImportError(
ImportError: Only macOS 13.5 and newer are supported, not 10.16

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx_lm/__init__.py", line 3, in <module>
    from .utils import convert, generate, load
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx_lm/utils.py", line 14, in <module>
    import mlx.core as mx
ImportError: initialization failed
```
去mlx文档找答案，执行`python -c "import platform; print(platform.processor())"`
打印`i386`
于是尝试让它打印 arm  
②运行
`CONDA_SUBDIR=osx-arm64 conda create -n bilibot python=3.10 -c conda-forge`
`conda activate bilibot`
`pip install -r requirements.txt`
又遇到问题1无法安装mlx，于是运行
`conda install -c conda-forge mlx`
报错
```
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides __osx >=13.3 needed by mlx-0.0.10-py310h3c7ea46_0

Could not solve for environment specs
The following package could not be installed
└─ mlx is not installable because it requires
   └─ __osx >=13.3 , which is missing on the system.
```

**Comment by obiscr** [comment]
一模一样的的问题，同样卡在这里。

**Comment by greenhand0403** [comment]
执行
`pip install`
报错
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx
所以我才执行
`conda install -c conda-forge mlx`

**Comment by greenhand0403** [comment]
参考这篇 issue 提到 macOS 需要 M 系列的芯片
['pip install mlx' does not seem to work correctly](https://github.com/ml-explore/mlx/issues/10#issuecomment-1843415420)

以及这篇 issue 提到运行起来需要 64G 内存
[想要在 linux&win 运行 B 友](https://github.com/linyiLYi/bilibot/issues/7#issuecomment-2107720563)

 MacBook2018 Intel Core i7 暂时搁置这个计划

其他可能有帮助的信息
[构建并安装MLX](https://ml-explore.github.io/mlx/build/html/install.html)
[anaconda文档](https://docs.anaconda.com/)
[如何删除旧的缓存版本的软件包？](https://cxc.cfa.harvard.edu/ciao/faq/conda_clean.html)
[如何为新的 conda 环境指定架构或平台？](https://stackoverflow.com/questions/65415996/how-to-specify-the-architecture-or-platform-for-a-new-conda-environment-apple)

**Comment by leyuan** [comment]
This worked for me for question 1
https://github.com/ml-explore/mlx/issues/10#issuecomment-1844194109

Using conda install gave me `i386` but this fix give me `arm` when do 
> python -c "import platform; print(platform.processor())"
